CREATE DATABASE FRUTELLA
GO

CREATE TABLE PRODUTO(
	[CODIGO DO PRODUTO] VARCHAR(8) PRIMARY KEY,
	NOME VARCHAR(30),
	EMBALAGEM VARCHAR(20),
	TAMANHO VARCHAR(10),
	SABOR VARCHAR(20),
	[PRECO UNITARIO] MONEY
)
GO

CREATE TABLE ESTOQUE(
	[ID ESTOQUE] INT PRIMARY KEY,
	[CODIGO DO PRODUTO] VARCHAR(8),
	QUANTIDADE INT,
	FORNECEDOR VARCHAR(30),
	[INVESTIMENTO UNITARIO] MONEY
)
GO

ALTER TABLE ESTOQUE ADD CONSTRAINT FK_CODIGOPRODUTO
FOREIGN KEY([CODIGO DO PRODUTO]) REFERENCES PRODUTO([CODIGO DO PRODUTO])
GO

CREATE TABLE CLIENTES(
	CPF VARCHAR(11) PRIMARY KEY,
	NOME VARCHAR(100),
	CELULAR VARCHAR(14),
	CEP VARCHAR(8),
	CIDADE VARCHAR(50),
	BAIRRO VARCHAR(60),
	RUA VARCHAR(100),
	[NUMERO DA CASA] VARCHAR(8),
	[LIMITE DE COMPRA ] MONEY,
	[PRIMEIRA COMPRA] BIT
)
GO

CREATE TABLE VENDAS(
	[ID VENDAS] INT PRIMARY KEY,
	[CPF CLIENTE] VARCHAR(11),
	[DATA VENDA] DATE,
	TOTAL MONEY
)
GO

ALTER TABLE [ITENS VENDAS] ADD CONSTRAINT FK_IDVENDAS
FOREIGN KEY([ID VENDAS]) REFERENCES VENDAS([ID VENDAS])
GO

CREATE TABLE [ITENS VENDAS](
	[ID ITEM VENDA] INT PRIMARY KEY,
	[ID VENDAS] INT,
	[CODIGO DO PRODUTO] VARCHAR(8),
	[PRECO UNITARIO] MONEY,
	QUANTIDADE INT,
	SUBTOTAL MONEY
)
GO

ALTER TABLE [ITENS VENDAS] ADD CONSTRAINT FK_IDVENDAS
FOREIGN KEY([ID VENDAS]) REFERENCES VENDAS([ID VENDAS])
GO

ALTER TABLE [ITENS VENDAS] ADD CONSTRAINT FK_CODIGO_PRODUTO
FOREIGN KEY([CODIGO DO PRODUTO]) REFERENCES PRODUTO([CODIGO DO PRODUTO])
GO

-- DDL 
ALTER TABLE VENDAS
ADD [MODO DE ENTREGA] VARCHAR(30)
GO

ALTER TABLE CLIENTES
ADD [SEXO] CHAR(1)
GO

  
ALTER TABLE VENDAS
ADD CONSTRAINT CHK_MODO_ENTREGA CHECK ([MODO DE ENTREGA] IN ('DELIVERY', 'RETIRADA'));
