ALTER TABLE VENDAS
ADD [MODO DE ENTREGA] VARCHAR(30)
GO

ALTER TABLE CLIENTES
ADD [SEXO] CHAR(1)
GO

  
ALTER TABLE VENDAS
ADD CONSTRAINT CHK_MODO_ENTREGA CHECK ([MODO DE ENTREGA] IN ('DELIVERY', 'RETIRADA'));
