-- Filtrar código do produto, preço de VENDA e qtd no estoque
SELECT E.[CODIGO DO PRODUTO],E.QUANTIDADE, P.[PRECO UNITARIO]
FROM ESTOQUE E
INNER JOIN PRODUTO P
ON E.[CODIGO DO PRODUTO] = P.[CODIGO DO PRODUTO]
WHERE E.QUANTIDADE > 0
GO

-- AGRUPANDO AS VENDAS POR CODIGO PARA MOSTRAR QUAL PRODUTO FOI MAIS VENDIDO
SELECT [CODIGO DO PRODUTO], SUM(SUBTOTAL) AS [VALOR TOTAL]
FROM [ITENS VENDAS]
GROUP BY [CODIGO DO PRODUTO]
WITH ROLLUP
GO

/*
Criar uma query com CASE e THEN que vai trazer os clientes
 e classificar por poder de compra:
ex: um cliente tem um limite de 800 reais de credito na loja classifique-o
 como “NÍVEL BAIXO” e assim por diante.
*/
SELECT NOME, [LIMITE DE COMPRA],
    CASE
        WHEN [LIMITE DE COMPRA] <= 800 THEN 'LIMITE BAIXO'
        WHEN [LIMITE DE COMPRA] BETWEEN 801 AND 1500 THEN 'LIMITE MÉDIO'
        ELSE 'LIMITE ALTO'
    END AS [PODER DE COMPRA] 
FROM CLIENTES 
ORDER BY [LIMITE DE COMPRA ]
