-- Filtrar código do produto, preço de VENDA e qtd no estoque
SELECT E.[CODIGO DO PRODUTO],E.QUANTIDADE, P.[PRECO UNITARIO]
FROM ESTOQUE E
INNER JOIN PRODUTO P
ON E.[CODIGO DO PRODUTO] = P.[CODIGO DO PRODUTO]
WHERE E.QUANTIDADE > 0
GO

-- AGRUPANDO AS VENDAS POR CODIGO PARA MOSTRAR QUAL PRODUTO FOI MAIS VENDIDO
SELECT [CODIGO DO PRODUTO], SUM(SUBTOTAL) AS [VALOR TOTAL]
FROM [ITENS VENDAS]
GROUP BY [CODIGO DO PRODUTO]
WITH ROLLUP
GO
