

CREATE TRIGGER AtualizarEstoque
on [ITENS VENDAS]
AFTER INSERT 
AS 
BEGIN
	-- Atualiza o estoque com base nasa informações inseridas
	UPDATE ESTOQUE 
	SET QUANTIDADE = ESTOQUE.QUANTIDADE - inserted.QUANTIDADE
	FROM ESTOQUE 
	INNER JOIN inserted ON ESTOQUE.[CODIGO DO PRODUTO] = inserted.[CODIGO DO PRODUTO]
	WHERE inserted.[ID ITEM VENDA] = inserted.[ID ITEM VENDA];
END;
GO

-- TRIGGER PARA QUANDO O CLIENTE FIZER A [PRIMEIRA COMPRA] O STATUS SER ATUALIZADO
CREATE TRIGGER AtualizaStatusCliente
ON [VENDAS]
AFTER INSERT 
AS 
BEGIN 
	UPDATE CLIENTES
	SET [PRIMEIRA COMPRA] = 1
	FROM CLIENTES C
	INNER JOIN INSERTED I
	ON C.CPF = I.[CPF CLIENTE]
	WHERE C.[PRIMEIRA COMPRA] = 0;
END
GO

/* CRIAR UMA TRIGGER PARA QUANDO UM ITEM NO ESTOQUE ESTIVER ABAIXO DE 10 DAR UM ALERTA

/* 
CRIAR UMA TRIGGER PARA QUANDO O CLIENTE FIZER VÁRIAS COMPRAS ACIMA DE CERTA %  DO LIMITE ATUAL
DO LIMITE AUMENTAR O LIMITE AUTOMATICAMENTE
*/